In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
#Set root correctly...
os.chdir(r"C:\Users\jamed\Documents\repos\lidar_2\LidarClassifcationForFloodModelling")

In [3]:
from RandLANetImplementation.data import modelData

In [4]:
model_data = modelData()

In [5]:
model_data.new_split()

tensor([   12956,    12957,    12958,  ..., 18694886, 18694887, 18694888])
tensor([  21843,   21844,   21845,  ..., 6163672, 6163673, 6163674])
<class 'torch.Tensor'>


In [6]:
model_data.next_fold()

tensor([ 6867397,  6867398,  6867399,  ..., 10869187, 10869188, 10869808])

In [ ]:
from RandLANetImplementation.modules import random_sample, get_knn_points
tensor_downsampled = random_sample(model_data.get_folds[0], 0.01)
points_withs_ns = get_knn_points(tensor_downsampled, model_data.test_set, 1000)

TypeError: 'DataFrame' object is not callable

In [8]:
points_withs_ns

tensor([[[-1.4123e+05,  1.1336e+05,  1.6190e+03,  ...,  1.1000e+01,
           4.5613e+05,  0.0000e+00],
         [-1.4125e+05,  1.1330e+05,  1.6630e+03,  ...,  1.0000e+01,
           4.5543e+05,  0.0000e+00],
         [-1.4119e+05,  1.1330e+05,  1.7030e+03,  ...,  1.0000e+01,
           4.5543e+05,  0.0000e+00],
         ...,
         [-1.4209e+05,  1.1361e+05,  1.6120e+03,  ...,  1.1000e+01,
           4.5613e+05,  0.0000e+00],
         [-1.4207e+05,  1.1304e+05,  1.6200e+03,  ...,  1.1000e+01,
           4.5613e+05,  0.0000e+00],
         [-1.4092e+05,  1.1252e+05,  1.6610e+03,  ...,  1.0000e+01,
           4.5543e+05,  0.0000e+00]],

        [[-1.7792e+05,  1.6699e+05,  1.2330e+03,  ...,  1.0000e+01,
           4.5544e+05,  0.0000e+00],
         [-1.7785e+05,  1.6699e+05,  1.2160e+03,  ...,  1.0000e+01,
           4.5544e+05,  0.0000e+00],
         [-1.7779e+05,  1.6699e+05,  1.2300e+03,  ...,  1.0000e+01,
           4.5544e+05,  0.0000e+00],
         ...,
         [-1.7669e+05,  1